### ISSUE TITLE
FileNotFoundErrorFileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by ggxxer** [TongkunGuan/CCD#13]
Hi, thank you for your contribution. When I try to pretrain CCD with ViT-Tiny, I meet this error: 
' FileNotFoundErrorFileNotFoundError: [Errno 2] No such file or directory: '/data/ggxx/OCR-CC/data_lmdb/training/label/Synth/': '
But I have moved the dataset to the specified path and modified 'CCD_vision_model_Tiny.yaml' accordingly. Does this error mean that my dataset was not successfully unzipped? What should I do to solve the problem?

**Comment by TongkunGuan** [comment]
> Hi, thank you for your contribution. When I try to pretrain CCD with ViT-Tiny, I meet this error: ' FileNotFoundErrorFileNotFoundError: [Errno 2] No such file or directory: '/data/ggxx/OCR-CC/data_lmdb/training/label/Synth/': ' But I have moved the dataset to the specified path and modified 'CCD_vision_model_Tiny.yaml' accordingly. Does this error mean that my dataset was not successfully unzipped? What should I do to solve the problem?

please give detailed error information.

**Comment by ggxxer** [comment]
[2024-04-11 16:02:33,141 train.py:52 INFO pre_tiny_65536] Construct dataset.
Traceback (most recent call last):
  File "train.py", line 457, in <module>
    train(config)
  File "train.py", line 53, in train
    train_dataloader = _get_databaunch(config)
  File "train.py", line 434, in _get_databaunch
    train_ds = _get_dataset(dataset_class, config.dataset_train_roots, True, config, **ds_kwargs)
  File "train.py", line 417, in _get_dataset
    subfolders = [f.path for f in os.scandir(p) if f.is_dir()]
FileNotFoundError: [Errno 2] No such file or directory: '/data/gx/OCR-CC/data_lmdb/training/label/Synth/'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3692921) of binary: /home/gx/anaconda3/envs/CCD/bin/python
Traceback (most recent call last):
  File "/home/gx/anaconda3/envs/CCD/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/gx/anaconda3/envs/CCD/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/gx/anaconda3/envs/CCD/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/gx/anaconda3/envs/CCD/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/gx/anaconda3/envs/CCD/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/gx/anaconda3/envs/CCD/lib/python3.7/site-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/home/gx/anaconda3/envs/CCD/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/gx/anaconda3/envs/CCD/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED

**Comment by ggxxer** [comment]
[2024-04-11 16:02:33,141 train.py:52 INFO pre_tiny_65536] Construct dataset.
Traceback (most recent call last):
  File "train.py", line 457, in <module>
    train(config)
  File "train.py", line 53, in train
    train_dataloader = _get_databaunch(config)
  File "train.py", line 434, in _get_databaunch
    train_ds = _get_dataset(dataset_class, config.dataset_train_roots, True, config, **ds_kwargs)
  File "train.py", line 417, in _get_dataset
    subfolders = [f.path for f in os.scandir(p) if f.is_dir()]
FileNotFoundError: [Errno 2] No such file or directory: '/data/gx/OCR-CC/data_lmdb/training/label/Synth/'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3692921) of binary: /home/gx/anaconda3/envs/CCD/bin/python
Traceback (most recent call last):
  File "/home/gx/anaconda3/envs/CCD/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/gx/anaconda3/envs/CCD/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/gx/anaconda3/envs/CCD/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/gx/anaconda3/envs/CCD/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/gx/anaconda3/envs/CCD/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/gx/anaconda3/envs/CCD/lib/python3.7/site-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/home/gx/anaconda3/envs/CCD/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/gx/anaconda3/envs/CCD/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED

**Comment by ggxxer** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '/data/gx/OCR-CC/data_lmdb/training/label/Synth/'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3692921) of binary: /home/gx/anaconda3/envs/CCD/bin/python
Traceback (most recent call last):
  File "/home/gx/anaconda3/envs/CCD/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/gx/anaconda3/envs/CCD/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/gx/anaconda3/envs/CCD/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/gx/anaconda3/envs/CCD/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/gx/anaconda3/envs/CCD/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/gx/anaconda3/envs/CCD/lib/python3.7/site-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/home/gx/anaconda3/envs/CCD/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/gx/anaconda3/envs/CCD/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED

**Comment by ggxxer** [comment]
<img width="814" alt="1712829811889" src="https://github.com/TongkunGuan/CCD/assets/153196709/331e99df-7ae7-4773-85af-0b6b28a0f90c">
